<?php

namespace common\models\loan;

/*
 * Class used to generate and validate documents like TIN certfictes, Assessment forms, etc
 */

use Yii;
use yii\db\ActiveRecord;
use common\models\revenue\AccountPayment;

//use yii\web\Controller;

/**
 * This is the model class for table "{{%document}}".
 *
 * @property int $id
 * @property int $filename
 * @property string $document_type
 * @property string $user_password
 * @property string $owner_password
 * @property int $lg_id
 * @property int $created_at
 * @property int $created_by
 */
class ElmsDocument extends ActiveRecord {

    /**
     * {@inheritdoc}
     */
    public static function tableName() {
        return '{{%document_generated}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules() {
        return [
            [['filename', 'document_type', 'created_at', 'created_by', 'application_id'], 'required'],
            [['created_at', 'created_by', 'document_type', 'loan_id'], 'integer'],
            [['user_password', 'owner_password', 'filename'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels() {
        return [
            'id' => 'ID',
            'filename' => 'Filename',
            'loan_id' => 'Application',
            'document_type' => 'Document Type',
            'user_password' => 'User Password',
            'owner_password' => 'Owner Password',
            'created_at' => 'Date Generated',
            'created_by' => 'Generated By',
        ];
    }

    /**
     * Register a new document in the database
     * @param string $filename Name of File
     * @param Int $doctype Document Type ID
     * @param Int $app_id Application ID
     * @return type
     */
    public static function createDocument($filename, $doctype, $app_id) {
        $doc = new ElmsDocument(
                [
            'filename' => $filename,
            'loan_id' => $app_id,
            'document_type' => $doctype,
            'created_at' => time(),
            'created_by' => Yii::$app->user->id
                ]
        );
        //try to save the document
        return $doc->save();
    }



    public static function generateDownloadableReport($layout, $report_title) {
        //Variables
        $code = time();
        //Generated By
        $generated_by = Yii::$app->formatter->asUser(Yii::$app->user->id);
        $upf_logo = Yii::getAlias('@url_htmlassets') . '/images/upf_logo.png';
        $header = "<div style='border-bottom:2px solid #888;'><div style='width:50%;float:left;'><img src='{$upf_logo}' style='height:35px;float:left;margin-right:5px;'/><h5 style='float:left;color:#090049;font-weight:bold;'>UGANDA POLICE FORCE NON-TAX REVENUE <br/>& CLASSIFIED REGISTRY DATABASE</h5></div><div style='width:50%;float:right;'><h5 style='text-align:right;font-weight:bold;color:#708090;text0shadow:1px 1px #000;'>{$report_title}</h5></div></div>";

        $config_params = array(
            'orientation' => 'L',
            'setAutoTopMargin' => true,
            'margin_left' => 12,
            'margin_right' => 10,
            'margin_top' => 0,
            'margin_bottom' => 10,
            'mode' => 'utf-8',
            'margin_header' => 2,
            'margin_footer' => 2,
        );

        $mpdf = new \Mpdf\Mpdf($config_params);
        // $mpdf->setAutoTopMargin = true;
        //Set page Header
        $mpdf->SetHTMLHeader($header);
        //Document Properties
        $mpdf->SetTitle("Generated from PORAS");
        //Show watermark to avoid this document being shared as a legitimate document
        //$mpdf->showWatermarkText = true;
        //$mpdf->SetWatermarkText('TESTING', 0.1);
        //Protect this document from modification
        //MPDF CSS
        $css = Yii::getAlias("@vendor") . "/kartik-v/yii2-mpdf/src/assets/kv-mpdf-bootstrap.css";
        $mpdf->WriteHTML(file_get_contents($css), 1);
        //Page Footer
        $mpdf->SetFooter("<p>Generated on {DATE D jS M Y} by {$generated_by}</p>|Page {PAGENO}|<barcode code='{$code}' type='C128A'/>");
        //Page Contents
        $mpdf->WriteHTML("<header style='position: relative; top: -20px;'>");
        $mpdf->WriteHtml($layout);

        //Save the file to disc
        return $mpdf->Output(uniqid() . '.pdf', 'D');
    }


    /**
     * @return common\models\User
     */
    public function getGeneratedBy() {
        return $this->hasOne(User::class, ['id' => 'created_by']);
    }



}
