<?php

use common\models\Reports;
use miloschuman\highcharts\Highcharts;
use yii\helpers\Url;
use yii\widgets\Pjax;
//Reports
$report = new Reports();
$this->title = "Dashboard";
$this->params['page_description'] = "Page Description here...";
//Top Performing
$by_gender = $report->getUser();

?>
<style>
    .widget-style3{border:1px solid #999;}
</style>
  <?php Pjax::begin(['id' => 'cardsGrid'])?>
<div class="row card-group-row">
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text"style="color:#5c5c5c;font-size:22px;">556677</div>
                <div class="text-muted mt-1" style="font-size:12px;"><a href="<?=Url::to(['properties/index']);?>" class="text-muted mt-1">NUMBER OF PROPERTIES</a></div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text" style="color:#5c5c5c;;font-size:22px;">4,556,666</div>
                <div class="text-muted mt-1"style="font-size:12px;"><a href="<?=Url::to(['user/index']);?>" class="text-muted mt-1">ACTIVE TENANTS</a></div>

            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text" style="color:#5c5c5c;font-size:22px;">55,000,000,000 UGX</div>
                <div class="text-muted mt-1"style="font-size:12px;">RENT COLLECTED</div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text" style="color:#5c5c5c;font-size:22px;">230,000,000 UGX</div>
                <div class="text-muted mt-1" style="font-size:12px;">RENT BALANCE </div>
            </div>
        </div>
    </div>
</div>

<div class="row card-group-row">
       <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text" style="color:#5c5c5c;font-size:22px;">5,500,000</div>
                <div class="text-muted mt-1" style="font-size:12px;"> RENT DUE</div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text" style="color:#5c5c5c;font-size:22px;">44</div>
                <div class="text-muted mt-1" style="font-size:12px;">MOVE OUTS</div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text" style="color:#5c5c5c;font-size:22px;">3,400,000,000</div>
                <div class="text-muted mt-1" style="font-size:12px;">EXPENSES</div>
            </div>
        </div>
    </div>

        <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text" style="font-size:22px;">92%</div>
                <div class="text-muted mt-1" style="font-size:12px;"> OCCUPANCY RATE</div>
            </div>
        </div>
    </div>


</div>


<div class="element-box" style='margin:10px;border:1px solid #ccc;'>
    <div class="element-info" style='border-bottom:1px solid #eee;margin-bottom: 5px;'>
        <div class="row align-items-center">
            <div class="col-lg-4">
                <div class="element-info-with-icon">
                    <div class="element-info-text">
                        <!--<div class="element-inner-desc">This is a summary of Revenue performance of the Uganda Police Force</div>-->
                        <?=
Highcharts::widget([
    'options' => [
        'chart' => [
            'type' => 'column',
        ],
        'title' => ['text' => 'TOTAL NUMBER OF TENANTS APPLICATIONS'],
        'subtitle' => [
            'text' => 'Generated By: TMS Online System',
        ],
        'xAxis' => [
            'categories' => array_column($report->requetsByInstitution(), 'username'),
            'crosshair' => true,
        ],
        'yAxis' => [
            'title' => ['text' => 'Number of Tenant Applications'],
        ],
        'series' => [
            [
                'name' => 'Disbursed',
                'color' => '#069',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Disbursed')),
            ],
            [
                'name' => 'Pending',
                'color' => '#ed8e09',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Pending')),
            ],
            [
                'name' => 'Approved',
                'color' => '#6aa66a',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Approved')),
            ],
            [
                'name' => 'Rejected',
                'color' => '#c96253',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Rejected')),
            ],

            [
                'name' => 'Offset',
                'color' => '#73b8f0',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Offset')),
            ],
            [
                'name' => 'Merged',
                'color' => '#6bc9c8',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Merged')),
            ],

        ],
        'credits' => ['enabled' => false],
    ],
]);
?>
                    </div>
                </div>
            </div>
            <div class="col-lg-8 col-lg-offset-2" style="padding-left: 30px;">
                <?=
Highcharts::widget([
    'options' => [
        'chart' => [
            'type' => 'column',
        ],
        'title' => ['text' => 'TOTAL NUMBER OF TENANTS APPLICATIONS'],
        'subtitle' => [
            'text' => 'Generated By: TMS Online System',
        ],
        'xAxis' => [
            'categories' => array_column($report->requetsByInstitution(), 'username'),
            'crosshair' => true,
        ],
        'yAxis' => [
            'title' => ['text' => 'Number of Tenant Applications'],
        ],
        'series' => [
            [
                'name' => 'Disbursed',
                'color' => '#069',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Disbursed')),
            ],
            [
                'name' => 'Pending',
                'color' => '#ed8e09',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Pending')),
            ],
            [
                'name' => 'Approved',
                'color' => '#6aa66a',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Approved')),
            ],
            [
                'name' => 'Rejected',
                'color' => '#c96253',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Rejected')),
            ],

            [
                'name' => 'Offset',
                'color' => '#73b8f0',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Offset')),
            ],
            [
                'name' => 'Merged',
                'color' => '#6bc9c8',
                'animation' => false,
                'data' => array_map('intval', array_column($report->requetsByInstitution(), 'Merged')),
            ],

        ],
        'credits' => ['enabled' => false],
    ],
]);
?>
            </div>
        </div>
    </div>
</div>
<?php
Pjax::end();
?>

<?php

$js = 'function refresh() {
     $.pjax.reload({container:"#cardsGrid"});
     setTimeout(refresh, 1000); // restart the function every 8 seconds
 }
 refresh();';
$this->registerJs($js, $this::POS_READY);
?>

