<?php

use yii\helpers\Html;
use miloschuman\highcharts\Highcharts;

$this->title = "Membership Dashboard";
$this->params['page_description'] = "Page Description here...";
?>
<style>
    .widget-style3{border:1px solid #999;}
</style>
<div class="row card-group-row">
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text-amount"><?= $pending_loans['pending_loans']; ?></div>
                <div class="text-muted mt-1">Applications pending</div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text-amount"><?= $approved_loans['approved_loans']; ?></div>
                <div class="text-muted mt-1">Loans Approved</div>
                <!-- <div class="text-stats text-success">51.5% <i class="material-icons">arrow_upward</i></div> -->
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text-amount"><?= $pending_clients['pending_clients']; ?></div>
                <div class="text-muted mt-1">Clients pending approval</div>
            </div>
        </div>
    </div>
    <div class="col-xl-3 col-md-6 card-group-row__col">
        <div class="card card-group-row__card card-body flex-row align-items-center">
            <div class="flex">
                <div class="text-amount"><?= $released_loans['released_loans']; ?></div>
                <div class="text-muted mt-1">Clients Approved</div>
            </div>
        </div>
    </div>
</div>

<div class="site-index">
    <div class="row">
        <div class="col-lg-12">
            <?=
            Highcharts::widget([
                'options' => [
                    'chart' => [
                        'type' => 'column'
                    ],
                    'title' => ['text' => 'TOTAL NUMBER OF LOAN APPLICATIONS'],
                    'subtitle' => [
                        'text' => 'Generated By: LMS Online System'
                    ],
                    'xAxis' => [
                        'categories' => array_column($report->requetsByInstitution(), 'name'),
                        'crosshair' => true
                    ],
                    'yAxis' => [
                        'title' => ['text' => 'Number of Loan Applications']
                    ],
                    'series' => [
                        [
                            'name' => 'Loan Applications',
                            'color' => '#069',
                            'data' => array_map('intval', array_column($report->requetsByInstitution(), 'total_request'))
                        ]
                    ],
                    'credits' => ['enabled' => false],
                ]
            ]);
            ?>
        </div>
    </div>

</div>
<h6>RECENTLY LOAN APPLICATIONS</h6>
<?=
$this->render('dashboard/index', ['searchModel' => $searchModel,
    'dataProvider' => $dataProvider]);
?>